// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmdJHaJsYMep1oYfDYRd2bDyOBDaMA8d4',
    appId: '1:727196949956:web:738e98494449bd60459891',
    messagingSenderId: '727196949956',
    projectId: 'gazetecim-app',
    authDomain: 'gazetecim-app.firebaseapp.com',
    storageBucket: 'gazetecim-app.appspot.com',
    measurementId: 'G-7SSK1B3S7S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcGCHPiamDaDM9rFR2qiGzTEVbzoAhWDw',
    appId: '1:727196949956:android:37dcaacc8fb18f61459891',
    messagingSenderId: '727196949956',
    projectId: 'gazetecim-app',
    storageBucket: 'gazetecim-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA52zdx4t4vrmmY52-eXlQ3xSPuLKwlByc',
    appId: '1:727196949956:ios:f1f1040eb7838f5a459891',
    messagingSenderId: '727196949956',
    projectId: 'gazetecim-app',
    storageBucket: 'gazetecim-app.appspot.com',
    iosBundleId: 'com.example.gazetecimApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA52zdx4t4vrmmY52-eXlQ3xSPuLKwlByc',
    appId: '1:727196949956:ios:b4b3bc6c234263ae459891',
    messagingSenderId: '727196949956',
    projectId: 'gazetecim-app',
    storageBucket: 'gazetecim-app.appspot.com',
    iosBundleId: 'com.example.gazetecimApp.RunnerTests',
  );
}
